#!/bin/sh
set -e

mkdir /etc/VirtStat/

touch /etc/VirtStat/servers
touch /etc/VirtStat/mail

chown -R root:root /etc/virtstat

chmod 600 /sbin/VirtStat
chmod +x /sbin/VirtStat
chmod 600 /sbin/memMV
chmod +x /sbin/memMV
chmod 600 /sbin/memlist
chmod +x /sbin/memlist

#DEBHELPER#

exit 0
