#!/bin/sh
set -e

mkdir /etc/VirtStat/

touch /etc/VirtStat/servers
touch /etc/VirtStat/mail

chown -R root:root /etc/virtstat

mv /sbin/VirtStat.sh /sbin/VirtStat
chmod 600 /sbin/VirtStat
chmod +x /sbin/VirtStat

#DEBHELPER#
